<#
.SYNOPSIS
  Install agentmemory-keeper as user-scoped scheduled tasks (no admin needed).

.DESCRIPTION
  Creates two scheduled tasks under the current user:
    - AgentmemoryKeeper          : at logon, launches keeper -Daemon (hidden)
    - AgentmemoryKeeperWatchdog  : every 5 min, restarts keeper if it died
  Generates a small VBS launcher so the PowerShell window never flashes.
#>

[CmdletBinding()]
param(
    [string]$TaskNameKeeper   = 'AgentmemoryKeeper',
    [string]$TaskNameWatchdog = 'AgentmemoryKeeperWatchdog',
    [string]$TaskNameWatcher  = 'AgentmemoryKeeperWatcher',
    [int]$WatchdogIntervalMinutes = 5
)

$ErrorActionPreference = 'Stop'
$ScriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$KeeperPs1   = Join-Path $ScriptRoot 'keeper.ps1'
$WatchdogPs1 = Join-Path $ScriptRoot 'watchdog.ps1'
$WatcherJs   = Join-Path $ScriptRoot 'watcher.mjs'
$LauncherVbs = Join-Path $ScriptRoot 'launch-hidden.vbs'

if (-not (Test-Path $KeeperPs1)) {
    throw "keeper.ps1 missing at $KeeperPs1"
}

# -------- Generate watchdog.ps1 (small, idempotent) -----------------------
$watchdogBody = @'
# Auto-generated by install.ps1. Restarts keeper if missing or stuck.
$ErrorActionPreference = 'Stop'
$root   = Split-Path -Parent $MyInvocation.MyCommand.Path
$keeper = Join-Path $root 'keeper.ps1'
$vbs    = Join-Path $root 'launch-hidden.vbs'

$running = @(Get-CimInstance Win32_Process -Filter "Name = 'powershell.exe' OR Name = 'pwsh.exe'" -ErrorAction SilentlyContinue |
    Where-Object { $_.CommandLine -and $_.CommandLine -match 'keeper\.ps1' -and $_.CommandLine -match '-Daemon' })

if ($running.Count -eq 0) {
    # Daemon not running: start it hidden.
    Start-Process -FilePath 'wscript.exe' -ArgumentList @("`"$vbs`"") -WindowStyle Hidden | Out-Null
}

# Belt-and-braces: do a one-shot health probe so we still recover even if
# the daemon is wedged in a way the keeper itself cannot detect (e.g. its
# loop is alive but Test-Health returns false for some reason).
& powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File $keeper -Once | Out-Null
exit 0
'@
Set-Content -Path $WatchdogPs1 -Value $watchdogBody -Encoding utf8

# -------- Generate launch-hidden.vbs --------------------------------------
$vbsBody = @"
' Auto-generated by install.ps1. Launches keeper.ps1 -Daemon with no window.
Set objShell = CreateObject("WScript.Shell")
objShell.Run "powershell.exe -NoProfile -ExecutionPolicy Bypass -File ""$KeeperPs1"" -Daemon", 0, False
"@
Set-Content -Path $LauncherVbs -Value $vbsBody -Encoding ascii

# Also a small launcher for the watchdog (no flash).
$WatchdogVbs = Join-Path $ScriptRoot 'launch-watchdog.vbs'
$wdVbsBody = @"
' Auto-generated by install.ps1. Launches watchdog with no window.
Set objShell = CreateObject("WScript.Shell")
objShell.Run "powershell.exe -NoProfile -ExecutionPolicy Bypass -File ""$WatchdogPs1""", 0, True
"@
Set-Content -Path $WatchdogVbs -Value $wdVbsBody -Encoding ascii

# -------- Generate launch-watcher.vbs (Node watcher, hidden) --------------
$node = if (Test-Path (Join-Path $env:ProgramFiles 'nodejs\node.exe')) {
    Join-Path $env:ProgramFiles 'nodejs\node.exe'
} else {
    (Get-Command node.exe -ErrorAction SilentlyContinue).Source
}
if (-not $node) {
    Write-Warning "node.exe not found; watcher task will be created but cannot run until Node is installed."
    $node = 'node.exe'
}
$WatcherVbs = Join-Path $ScriptRoot 'launch-watcher.vbs'
$watcherVbsBody = @"
' Auto-generated by install.ps1. Launches the transcript watcher with no window.
Set objShell = CreateObject("WScript.Shell")
objShell.Run """$node"" ""$WatcherJs""", 0, False
"@
Set-Content -Path $WatcherVbs -Value $watcherVbsBody -Encoding ascii

# -------- Remove existing tasks (idempotent) ------------------------------
foreach ($name in @($TaskNameKeeper, $TaskNameWatchdog, $TaskNameWatcher)) {
    try {
        Unregister-ScheduledTask -TaskName $name -Confirm:$false -ErrorAction Stop
        Write-Host "Removed existing task: $name"
    } catch {}
}

# -------- Build common settings --------------------------------------------
$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -DontStopOnIdleEnd `
    -ExecutionTimeLimit (New-TimeSpan -Hours 0) `
    -RestartCount 99 `
    -RestartInterval (New-TimeSpan -Minutes 1) `
    -MultipleInstances IgnoreNew

$principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" -LogonType Interactive -RunLevel Limited

# -------- Task 1: keeper at logon ------------------------------------------
$keeperAction = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument ('"{0}"' -f $LauncherVbs)
$keeperTrigger = New-ScheduledTaskTrigger -AtLogOn -User "$env:USERDOMAIN\$env:USERNAME"

Register-ScheduledTask -TaskName $TaskNameKeeper `
    -Action $keeperAction `
    -Trigger $keeperTrigger `
    -Settings $settings `
    -Principal $principal `
    -Description 'Keeps agentmemory daemon alive across sleep/wake, network changes, VPN, BleachBit, etc.' | Out-Null
Write-Host "Installed task: $TaskNameKeeper"

# Best-effort: also add a workstation-unlock trigger via XML edit.
# (Register-ScheduledTask rejects CIM-built session triggers due to PSTypeName checks,
# so we mutate the task definition after registration.)
try {
    $task = Get-ScheduledTask -TaskName $TaskNameKeeper
    $xml  = Export-ScheduledTask -TaskName $TaskNameKeeper
    if ($xml -notmatch 'SessionStateChangeTrigger') {
        $unlockXml = @"
  <SessionStateChangeTrigger>
    <Enabled>true</Enabled>
    <StateChange>SessionUnlock</StateChange>
    <UserId>$env:USERDOMAIN\$env:USERNAME</UserId>
  </SessionStateChangeTrigger>
"@
        $newXml = $xml -replace '(</Triggers>)', ($unlockXml + "`r`n  `$1")
        Register-ScheduledTask -TaskName $TaskNameKeeper -Xml $newXml -User "$env:USERDOMAIN\$env:USERNAME" -Force | Out-Null
        Write-Host "  + added workstation-unlock trigger"
    }
} catch {
    Write-Warning "Could not add unlock trigger (logon + watchdog is enough): $($_.Exception.Message)"
}

# -------- Task 2: watchdog every N minutes ---------------------------------
# Use schtasks.exe because Register-ScheduledTask rejects indefinite repetition.
$schtasksTr = 'wscript.exe "{0}"' -f $WatchdogVbs
$schtasksOut = & schtasks.exe /Create /TN $TaskNameWatchdog /SC MINUTE /MO $WatchdogIntervalMinutes /TR $schtasksTr /F /RL LIMITED 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Warning ("schtasks.exe failed: {0}" -f ($schtasksOut -join "`n"))
} else {
    Write-Host "Installed task: $TaskNameWatchdog (every $WatchdogIntervalMinutes min)"
}

# -------- Task 3: transcript watcher (at logon, persists across runs) -----
$watcherAction = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument ('"{0}"' -f $WatcherVbs)
$watcherTrigger = New-ScheduledTaskTrigger -AtLogOn -User "$env:USERDOMAIN\$env:USERNAME"
Register-ScheduledTask -TaskName $TaskNameWatcher `
    -Action $watcherAction `
    -Trigger $watcherTrigger `
    -Settings $settings `
    -Principal $principal `
    -Description 'Streams Cursor and Codex transcript activity into agentmemory in near-real-time so the Token Savings stat reflects live work.' | Out-Null
Write-Host "Installed task: $TaskNameWatcher (at logon)"

# -------- Kick off immediately --------------------------------------------
Start-ScheduledTask -TaskName $TaskNameKeeper
Start-ScheduledTask -TaskName $TaskNameWatcher
Write-Host ""
Write-Host "Install complete. Keeper + watcher are now running in the background." -ForegroundColor Green
Write-Host "  ctl.ps1 status   - see what's running"
Write-Host "  ctl.ps1 savings  - current token-savings number"
Write-Host "  ctl.ps1 watcher  - watcher status"
Write-Host "  ctl.ps1 logs     - tail keeper log"
Write-Host "  ctl.ps1 doctor   - full diagnostic"
