<#
.SYNOPSIS
  Install agentmemory-keeper as user-scoped scheduled tasks (no admin needed).

.DESCRIPTION
  Creates two scheduled tasks under the current user:
    - AgentmemoryKeeper          : at logon, launches keeper -Daemon (hidden)
    - AgentmemoryKeeperWatchdog  : every 5 min, restarts keeper if it died
  Generates a small VBS launcher so the PowerShell window never flashes.
#>

[CmdletBinding()]
param(
    [string]$TaskNameKeeper   = 'AgentmemoryKeeper',
    [string]$TaskNameWatchdog = 'AgentmemoryKeeperWatchdog',
    [int]$WatchdogIntervalMinutes = 5
)

$ErrorActionPreference = 'Stop'
$ScriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$KeeperPs1  = Join-Path $ScriptRoot 'keeper.ps1'
$WatchdogPs1= Join-Path $ScriptRoot 'watchdog.ps1'
$LauncherVbs= Join-Path $ScriptRoot 'launch-hidden.vbs'

if (-not (Test-Path $KeeperPs1)) {
    throw "keeper.ps1 missing at $KeeperPs1"
}

# -------- Generate watchdog.ps1 (small, idempotent) -----------------------
$watchdogBody = @'
# Auto-generated by install.ps1. Restarts keeper if missing or stuck.
$ErrorActionPreference = 'Stop'
$root   = Split-Path -Parent $MyInvocation.MyCommand.Path
$keeper = Join-Path $root 'keeper.ps1'
$vbs    = Join-Path $root 'launch-hidden.vbs'

$running = @(Get-CimInstance Win32_Process -Filter "Name = 'powershell.exe' OR Name = 'pwsh.exe'" -ErrorAction SilentlyContinue |
    Where-Object { $_.CommandLine -and $_.CommandLine -match 'keeper\.ps1' -and $_.CommandLine -match '-Daemon' })

if ($running.Count -eq 0) {
    # Daemon not running: start it hidden.
    Start-Process -FilePath 'wscript.exe' -ArgumentList @("`"$vbs`"") -WindowStyle Hidden | Out-Null
}

# Belt-and-braces: do a one-shot health probe so we still recover even if
# the daemon is wedged in a way the keeper itself cannot detect (e.g. its
# loop is alive but Test-Health returns false for some reason).
& powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File $keeper -Once | Out-Null
exit 0
'@
Set-Content -Path $WatchdogPs1 -Value $watchdogBody -Encoding utf8

# -------- Generate launch-hidden.vbs --------------------------------------
$vbsBody = @"
' Auto-generated by install.ps1. Launches keeper.ps1 -Daemon with no window.
Set objShell = CreateObject("WScript.Shell")
objShell.Run "powershell.exe -NoProfile -ExecutionPolicy Bypass -File ""$KeeperPs1"" -Daemon", 0, False
"@
Set-Content -Path $LauncherVbs -Value $vbsBody -Encoding ascii

# Also a small launcher for the watchdog (no flash).
$WatchdogVbs = Join-Path $ScriptRoot 'launch-watchdog.vbs'
$wdVbsBody = @"
' Auto-generated by install.ps1. Launches watchdog with no window.
Set objShell = CreateObject("WScript.Shell")
objShell.Run "powershell.exe -NoProfile -ExecutionPolicy Bypass -File ""$WatchdogPs1""", 0, True
"@
Set-Content -Path $WatchdogVbs -Value $wdVbsBody -Encoding ascii

# -------- Remove existing tasks (idempotent) ------------------------------
foreach ($name in @($TaskNameKeeper, $TaskNameWatchdog)) {
    try {
        Unregister-ScheduledTask -TaskName $name -Confirm:$false -ErrorAction Stop
        Write-Host "Removed existing task: $name"
    } catch {}
}

# -------- Build common settings --------------------------------------------
$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -DontStopOnIdleEnd `
    -ExecutionTimeLimit (New-TimeSpan -Hours 0) `
    -RestartCount 99 `
    -RestartInterval (New-TimeSpan -Minutes 1) `
    -MultipleInstances IgnoreNew

$principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" -LogonType Interactive -RunLevel Limited

# -------- Task 1: keeper at logon ------------------------------------------
$keeperAction = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument ('"{0}"' -f $LauncherVbs)
$keeperTriggers = @(
    (New-ScheduledTaskTrigger -AtLogOn -User "$env:USERDOMAIN\$env:USERNAME")
)

# Add workstation-unlock trigger via CIM (no admin needed).
try {
    $unlockTrigger = New-CimInstance -ClassName MSFT_TaskSessionStateChangeTrigger `
        -Namespace 'Root/Microsoft/Windows/TaskScheduler' `
        -ClientOnly `
        -Property @{
            Enabled    = $true
            StateChange = 8   # 8 = SessionUnlock
            UserId     = "$env:USERDOMAIN\$env:USERNAME"
        }
    $keeperTriggers += $unlockTrigger
} catch {
    Write-Warning "Could not add workstation-unlock trigger: $($_.Exception.Message). Logon trigger alone is sufficient."
}

Register-ScheduledTask -TaskName $TaskNameKeeper `
    -Action $keeperAction `
    -Trigger $keeperTriggers `
    -Settings $settings `
    -Principal $principal `
    -Description 'Keeps agentmemory daemon alive across sleep/wake, network changes, VPN, BleachBit, etc.' | Out-Null
Write-Host "Installed task: $TaskNameKeeper"

# -------- Task 2: watchdog every N minutes ---------------------------------
$wdAction = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument ('"{0}"' -f $WatchdogVbs)
$wdStart = (Get-Date).AddMinutes(1)
$wdTrigger = New-ScheduledTaskTrigger -Once -At $wdStart `
    -RepetitionInterval (New-TimeSpan -Minutes $WatchdogIntervalMinutes) `
    -RepetitionDuration (New-TimeSpan -Days 36500)

Register-ScheduledTask -TaskName $TaskNameWatchdog `
    -Action $wdAction `
    -Trigger $wdTrigger `
    -Settings $settings `
    -Principal $principal `
    -Description 'Watchdog: restarts agentmemory-keeper if it ever dies, every 5 minutes.' | Out-Null
Write-Host "Installed task: $TaskNameWatchdog (every $WatchdogIntervalMinutes min)"

# -------- Kick off immediately --------------------------------------------
Start-ScheduledTask -TaskName $TaskNameKeeper
Write-Host ""
Write-Host "Install complete. The keeper is now running in the background." -ForegroundColor Green
Write-Host "  ctl.ps1 status   - see what's running"
Write-Host "  ctl.ps1 logs     - tail keeper log"
Write-Host "  ctl.ps1 doctor   - full diagnostic"
