' Auto-generated by install.ps1. Launches the transcript watcher with no window.
Set objShell = CreateObject("WScript.Shell")
objShell.Run """C:\Program Files\nodejs\node.exe"" ""C:\code\agentmemory-keeper\watcher.mjs""", 0, False
